[build]
  command = "npm install && npm run build"
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[functions.chat]
  included_files = ["node_modules/groq-sdk/**"]
  external_node_modules = ["groq-sdk"]
  timeout = 30

[[plugins]]
  package = "@netlify/plugin-functions-core"

[build.environment]
  NODE_ENV = "production"
