[build]
  publish = "public" 
  functions = "netlify/functions"  

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[functions."script"]
  included_files = ["node_modules/groq-sdk/**"]
  external_node_modules = ["groq-sdk"]
  timeout = 30  

[context.production.environment]
  NODE_ENV = "production"  
